sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

#    sky:
#     alioss:
#    endpoint: ${sky.alioss.endpoint}
#    access-key-id: ${sky.alioss.access-key-id}
#    access-key-secret: ${sky.alioss.access-key-secret}
#    bucket-name: ${sky.alioss.bucket-name}

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJa6ie8ckENtgxeaZy9
    access-key-secret: WWBQYDVvosPYl6yV4o3C74qpM2PpzO
    bucket-name: hmleadnewsrich
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wxb56d8f72a06d8f6f
    secret: 2a7708749b253fff82da46298ce9151e
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php

