sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

#    sky:
#     alioss:
#    endpoint: ${sky.alioss.endpoint}
#    access-key-id: ${sky.alioss.access-key-id}
#    access-key-secret: ${sky.alioss.access-key-secret}
#    bucket-name: ${sky.alioss.bucket-name}
    sky:
      alioss:
        endpoint: oss-cn-beijing.aliyuncs.com
        access-key-id: LTAI5tJa6ie8ckENtgxeaZy9
        access-key-secret: WWBQYDVvosPYl6yV4o3C74qpM2PpzO
        bucket-name: hmleadnewsrich

